CLINICAL_RANGES = {
    'age': {'min': 0, 'max': 120},
    'height': {'min': 0.50, 'max': 2.50},
    'weight': {'min': 20.0, 'max': 300.0},
    'bmi': {'min': 10.0, 'max': 60.0},
    'systolic_bp': {'min': 60, 'max': 280},
    'diastolic_bp': {'min': 30, 'max': 180},
    'heart_rate': {'min': 30, 'max': 250},
    'oxygen_saturation': {'min': 50, 'max': 100},
    'glucose': {'min': 20.0, 'max': 600.0},
    'cholesterol': {'min': 50.0, 'max': 500.0},
    'cholesterol_ldl': {'min': 10.0, 'max': 350.0},
    'cholesterol_hdl': {'min': 5.0, 'max': 120.0},
    'triglycerides': {'min': 20.0, 'max': 2000.0},
    'hemoglobin': {'min': 5.0, 'max': 20.0},
    'creatinine': {'min': 0.1, 'max': 15.0},
}

CLINICAL_ALERT_RULES = [
    {'parameter': 'systolic_bp', 'condition': '>=', 'threshold': 180, 'severity': 'critical', 'alert_type': 'Hipertensión Crítica'},
    {'parameter': 'systolic_bp', 'condition': '>=', 'threshold': 140, 'severity': 'warning', 'alert_type': 'Hipertensión'},
    {'parameter': 'glucose', 'condition': '>=', 'threshold': 300, 'severity': 'critical', 'alert_type': 'Hiperglucemia Crítica'},
    {'parameter': 'glucose', 'condition': '>=', 'threshold': 126, 'severity': 'warning', 'alert_type': 'Hiperglucemia'},
    {'parameter': 'oxygen_saturation', 'condition': '<=', 'threshold': 85, 'severity': 'critical', 'alert_type': 'Hipoxia Crítica'},
    {'parameter': 'oxygen_saturation', 'condition': '<=', 'threshold': 90, 'severity': 'warning', 'alert_type': 'Hipoxia'},
    {'parameter': 'heart_rate', 'condition': '>=', 'threshold': 120, 'severity': 'warning', 'alert_type': 'Taquicardia'},
    {'parameter': 'heart_rate', 'condition': '<=', 'threshold': 50, 'severity': 'warning', 'alert_type': 'Bradicardia'},
    {'parameter': 'bmi', 'condition': '>=', 'threshold': 40, 'severity': 'warning', 'alert_type': 'Obesidad Mórbida'},
    {'parameter': 'cholesterol', 'condition': '>=', 'threshold': 240, 'severity': 'warning', 'alert_type': 'Hipercolesterolemia'},
]

DIAGNOSIS_MAPPING = {
    'hipertension': 'Hypertension',
    'hipertensión': 'Hypertension',
    'hypertension': 'Hypertension',
    'diabetes': 'Diabetes Mellitus',
    'diabettes': 'Diabetes Mellitus',
    'diabetis': 'Diabetes Mellitus',
    'dm tipo 2': 'Diabetes Mellitus Type 2',
    'dm2': 'Diabetes Mellitus Type 2',
    'obesidad': 'Obesity',
    'obesidad morbida': 'Morbid Obesity',
    'obesidad mórbida': 'Morbid Obesity',
    'insuficiencia cardiaca': 'Heart Failure',
    'insuficiencia cardíaca': 'Heart Failure',
    'cardiopatia': 'Heart Disease',
    'cardiopatía': 'Heart Disease',
    'cardiopatia isquemica': 'Ischemic Heart Disease',
    'cardiopatía isquémica': 'Ischemic Heart Disease',
    'epoc': 'COPD',
    'enfermedad pulmonar': 'Lung Disease',
    'asma': 'Asthma',
    'cancer': 'Cancer',
    'cáncer': 'Cancer',
    'artritis': 'Arthritis',
    'artritis reumatoide': 'Rheumatoid Arthritis',
    'depresion': 'Depression',
    'depresión': 'Depression',
    'ansiedad': 'Anxiety',
    'enfermedad renal': 'Chronic Kidney Disease',
    'insuficiencia renal': 'Chronic Kidney Disease',
    'enfermedad hepatica': 'Liver Disease',
    'enfermedad hepática': 'Liver Disease',
    'hipotiroidismo': 'Hypothyroidism',
    'hipertiroidismo': 'Hyperthyroidism',
    'anemia': 'Anemia',
}

DIAGNOSIS_CODES = {
    'Hypertension': 'I10',
    'Diabetes Mellitus': 'E11',
    'Diabetes Mellitus Type 2': 'E11',
    'Obesity': 'E66',
    'Morbid Obesity': 'E66.0',
    'Heart Failure': 'I50',
    'Heart Disease': 'I25',
    'Ischemic Heart Disease': 'I25',
    'COPD': 'J44',
    'Lung Disease': 'J98',
    'Asthma': 'J45',
    'Cancer': 'C80',
    'Arthritis': 'M19',
    'Rheumatoid Arthritis': 'M05',
    'Depression': 'F32',
    'Anxiety': 'F41',
    'Chronic Kidney Disease': 'N18',
    'Liver Disease': 'K76',
    'Hypothyroidism': 'E03',
    'Hyperthyroidism': 'E05',
    'Anemia': 'D64',
}

BMI_CATEGORIES = [
    (0, 18.5, 'underweight', 'Bajo peso'),
    (18.5, 25, 'normal', 'Normal'),
    (25, 30, 'overweight', 'Sobrepeso'),
    (30, 35, 'obese_i', 'Obesidad Grado I'),
    (35, 40, 'obese_ii', 'Obesidad Grado II'),
    (40, float('inf'), 'obese_iii', 'Obesidad Grado III'),
]

RISK_RULES = {
    'critical': [
        ('systolic_bp', '>=', 180),
        ('oxygen_saturation', '<=', 85),
        ('glucose', '>=', 300),
    ],
    'high': [
        ('systolic_bp', '>=', 160),
        ('glucose', '>=', 200),
        ('bmi', '>=', 40),
        ('cholesterol', '>=', 300),
    ],
    'medium': [
        ('systolic_bp', '>=', 140),
        ('glucose', '>=', 126),
        ('bmi', '>=', 30),
        ('smoking', '==', True),
        ('family_history', '==', True),
    ],
}

NORMAL_VALUES = {
    'systolic_bp': 120,
    'diastolic_bp': 80,
    'heart_rate': 75,
    'oxygen_saturation': 97,
    'glucose': 95.0,
    'cholesterol': 190.0,
    'cholesterol_ldl': 100.0,
    'cholesterol_hdl': 45.0,
    'triglycerides': 150.0,
    'hemoglobin': 14.0,
    'creatinine': 0.9,
    'height': 1.65,
    'weight': 70.0,
}
