# Generated by Django 5.2.15 on 2026-06-04 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('source_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('api', 'API'), ('manual', 'Manual')], max_length=20, verbose_name='tipo')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='archivo')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='nombre original')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='tamaño (bytes)')),
                ('row_count', models.IntegerField(blank=True, null=True, verbose_name='filas')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='cargado por')),
            ],
            options={
                'verbose_name': 'fuente de datos',
                'verbose_name_plural': 'fuentes de datos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETLExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('extracting', 'Extrayendo'), ('transforming', 'Transformando'), ('loading', 'Cargando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='estado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completado en')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='duración (s)')),
                ('records_read', models.IntegerField(default=0, verbose_name='registros leídos')),
                ('records_processed', models.IntegerField(default=0, verbose_name='registros procesados')),
                ('records_loaded', models.IntegerField(default=0, verbose_name='registros cargados')),
                ('records_failed', models.IntegerField(default=0, verbose_name='registros fallidos')),
                ('duplicates_removed', models.IntegerField(default=0, verbose_name='duplicados eliminados')),
                ('errors_corrected', models.IntegerField(default=0, verbose_name='errores corregidos')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='puntaje calidad')),
                ('error_message', models.TextField(blank=True, verbose_name='mensaje error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ejecutado por')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='etl.datasource', verbose_name='fuente')),
            ],
            options={
                'verbose_name': 'ejecución ETL',
                'verbose_name_plural': 'ejecuciones ETL',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='métrica')),
                ('metric_value', models.FloatField(verbose_name='valor')),
                ('threshold_min', models.FloatField(blank=True, null=True, verbose_name='umbral mínimo')),
                ('threshold_max', models.FloatField(blank=True, null=True, verbose_name='umbral máximo')),
                ('passed', models.BooleanField(default=True, verbose_name='aprobado')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='detalles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='etl.etlexecution', verbose_name='ejecución')),
            ],
            options={
                'verbose_name': 'métrica de calidad',
                'verbose_name_plural': 'métricas de calidad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], default='info', max_length=10, verbose_name='nivel')),
                ('phase', models.CharField(blank=True, max_length=20, verbose_name='fase')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='detalles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='etl.etlexecution', verbose_name='ejecución')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='etl.datasource', verbose_name='fuente')),
            ],
            options={
                'verbose_name': 'log ETL',
                'verbose_name_plural': 'logs ETL',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'phase'], name='etl_etllog_level_b76750_idx'), models.Index(fields=['execution', 'level'], name='etl_etllog_executi_423f00_idx')],
            },
        ),
    ]
