# Generated by Django 6.0.6 on 2026-06-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='file_content',
            field=models.BinaryField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='file_content_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nombre archivo'),
        ),
    ]
