# Generated by Django 5.2.15 on 2026-06-04 13:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True, verbose_name='ID del paciente')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellidos')),
                ('document_type', models.CharField(default='CC', max_length=20, verbose_name='tipo documento')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='número documento')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='edad')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='sexo')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='tipo sanguíneo')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.50')), django.core.validators.MaxValueValidator(Decimal('2.50'))], verbose_name='altura (m)')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('20.0')), django.core.validators.MaxValueValidator(Decimal('300.0'))], verbose_name='peso (kg)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('bmi_category', models.CharField(blank=True, choices=[('underweight', 'Bajo peso'), ('normal', 'Normal'), ('overweight', 'Sobrepeso'), ('obese_i', 'Obesidad Grado I'), ('obese_ii', 'Obesidad Grado II'), ('obese_iii', 'Obesidad Grado III')], max_length=20, null=True, verbose_name='categoría IMC')),
                ('systolic_bp', models.IntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(280)], verbose_name='presión sistólica')),
                ('diastolic_bp', models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)], verbose_name='presión diastólica')),
                ('heart_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='frecuencia cardíaca')),
                ('oxygen_saturation', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='saturación oxígeno (%)')),
                ('glucose', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('20.0')), django.core.validators.MaxValueValidator(Decimal('600.0'))], verbose_name='glucosa (mg/dL)')),
                ('cholesterol', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('50.0')), django.core.validators.MaxValueValidator(Decimal('500.0'))], verbose_name='colesterol total (mg/dL)')),
                ('cholesterol_ldl', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='colesterol LDL (mg/dL)')),
                ('cholesterol_hdl', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='colesterol HDL (mg/dL)')),
                ('triglycerides', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='triglicéridos (mg/dL)')),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='hemoglobina (g/dL)')),
                ('creatinine', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='creatinina (mg/dL)')),
                ('diagnosis', models.TextField(blank=True, verbose_name='diagnóstico principal')),
                ('diagnosis_code', models.CharField(blank=True, max_length=20, verbose_name='código diagnóstico')),
                ('comorbidities', models.TextField(blank=True, null=True, verbose_name='comorbilidades')),
                ('smoking', models.BooleanField(default=False, verbose_name='tabaquismo')),
                ('alcohol_consumption', models.BooleanField(default=False, verbose_name='consumo de alcohol')),
                ('physical_activity', models.BooleanField(default=False, verbose_name='actividad física')),
                ('family_history', models.BooleanField(default=False, verbose_name='antecedentes familiares')),
                ('risk_category', models.CharField(blank=True, choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=20, null=True, verbose_name='categoría de riesgo')),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='puntaje de riesgo')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='archivo origen')),
                ('is_processed', models.BooleanField(default=False, verbose_name='procesado')),
                ('is_valid', models.BooleanField(default=True, verbose_name='válido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_id', 'document_number'], name='patients_pa_patient_e78cc4_idx'), models.Index(fields=['risk_category'], name='patients_pa_risk_ca_71e690_idx'), models.Index(fields=['diagnosis_code'], name='patients_pa_diagnos_180340_idx'), models.Index(fields=['age', 'gender'], name='patients_pa_age_f9bd96_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClinicalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100, verbose_name='tipo de alerta')),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('critical', 'Crítico')], max_length=20, verbose_name='severidad')),
                ('description', models.TextField(verbose_name='descripción')),
                ('parameter', models.CharField(max_length=50, verbose_name='parámetro')),
                ('value', models.CharField(max_length=50, verbose_name='valor')),
                ('threshold', models.CharField(max_length=50, verbose_name='umbral')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resuelta en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'alerta clínica',
                'verbose_name_plural': 'alertas clínicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
