# Generated by Django 6.0.6 on 2026-06-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cholesterol_hdl',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cholesterol_ldl',
        ),
    ]
