# Generated by Django 5.2.15 on 2026-06-04 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('model_type', models.CharField(choices=[('random_forest', 'Random Forest'), ('logistic_regression', 'Regresión Logística'), ('decision_tree', 'Árbol de Decisión')], max_length=50, verbose_name='tipo de modelo')),
                ('target_variable', models.CharField(choices=[('risk_category', 'Categoría de Riesgo'), ('hypertension', 'Hipertensión'), ('diabetes', 'Diabetes')], max_length=50, verbose_name='variable objetivo')),
                ('version', models.CharField(max_length=20, verbose_name='versión')),
                ('file_path', models.CharField(max_length=255, verbose_name='ruta del modelo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='accuracy')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='precision')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='recall')),
                ('f1_score', models.FloatField(blank=True, null=True, verbose_name='f1-score')),
                ('roc_auc', models.FloatField(blank=True, null=True, verbose_name='ROC-AUC')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='parámetros')),
                ('feature_importance', models.JSONField(blank=True, null=True, verbose_name='importancia de variables')),
                ('confusion_matrix', models.JSONField(blank=True, null=True, verbose_name='matriz de confusión')),
                ('classification_report', models.JSONField(blank=True, null=True, verbose_name='reporte de clasificación')),
                ('training_records', models.IntegerField(blank=True, null=True, verbose_name='registros entrenamiento')),
                ('test_records', models.IntegerField(blank=True, null=True, verbose_name='registros prueba')),
                ('training_duration', models.FloatField(blank=True, null=True, verbose_name='duración entrenamiento (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='entrenado por')),
            ],
            options={
                'verbose_name': 'modelo ML',
                'verbose_name_plural': 'modelos ML',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(verbose_name='datos de entrada')),
                ('predicted_risk', models.CharField(max_length=20, verbose_name='riesgo predecido')),
                ('predicted_probability', models.FloatField(blank=True, null=True, verbose_name='probabilidad predecida')),
                ('probabilities', models.JSONField(blank=True, null=True, verbose_name='probabilidades por clase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml.mlmodelregistry')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'predicción ML',
                'verbose_name_plural': 'predicciones ML',
                'ordering': ['-created_at'],
            },
        ),
    ]
