# Generated by Django 5.2.15 on 2026-06-10 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, max_length=20, null=True, verbose_name='rol del usuario')),
                ('action', models.CharField(choices=[('create', 'Crear'), ('read', 'Leer'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('export', 'Exportar'), ('execute', 'Ejecutar'), ('train', 'Entrenar'), ('predict', 'Predecir')], max_length=20, verbose_name='acción')),
                ('module', models.CharField(max_length=50, verbose_name='módulo')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='tipo de recurso')),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del recurso')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('success', models.BooleanField(default=True, verbose_name='éxito')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='detalles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx'), models.Index(fields=['action', 'module'], name='core_auditl_action_f9c578_idx'), models.Index(fields=['user_role'], name='core_auditl_user_ro_1ef6f2_idx'), models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx')],
            },
        ),
    ]
